# Enhanced Schlage Invoice Processor Configuration Template
# This configuration allows customization for different Schlage invoice formats

patterns:
  # Invoice number patterns - ordered by specificity
  invoice_number:
    - 'INVOICE#\s*(\d+)'
    - 'INVOICE\s*#\s*(\d+)'
    - 'INVOICE\s*NUMBER\s*(\d+)'
    - '(\d{7,8})\s+\d{1,2}-[A-Z]{3}-\d{2}'  # Number before date pattern
    - 'ALLEGION.*?(\d{7,8})'  # Number after ALLEGION
    - '(\d{6,9})'  # Generic number pattern (lowest priority)

  # Date patterns
  invoice_date:
    - 'INVOICE\s*DATE\s*(\d{1,2}-[A-Z]{3}-\d{2})'
    - 'DATE\s*(\d{1,2}-[A-Z]{3}-\d{2})'
    - '(\d{1,2}-[A-Z]{3}-\d{2})'
    - '(\d{1,2}/\d{1,2}/\d{2,4})'
    - '(\d{4}-\d{2}-\d{2})'

  # Order information
  order_number:
    - 'ORDER#\s*(\d+)'
    - 'ORDER\s*#\s*(\d+)'
    - 'ORDER\s*NUMBER\s*(\d+)'
    - 'ORDER\s*NO\s*(\d+)'

  customer_po:
    - 'CUSTOMER\s*PO#\s*([A-Z0-9-]+)'
    - 'PO#\s*([A-Z0-9-]+)'
    - 'PO\s*NUMBER\s*([A-Z0-9-]+)'
    - 'PURCHASE\s*ORDER\s*([A-Z0-9-]+)'

  # Tracking and shipping
  tracking_number:
    - '(1Z[A-Z0-9]{16})'  # UPS tracking
    - 'UPS.*?(1Z[A-Z0-9]{16})'
    - 'TRACKING.*?(1Z[A-Z0-9]{16})'
    - 'FEDEX.*?(\d{12,14})'  # FedEx tracking
    - 'USPS.*?(\d{20,22})'  # USPS tracking

  # Financial amounts
  amounts:
    - '(\d{1,3}(?:,\d{3})*\.\d{2})'  # Standard currency format
    - '(\d+\.\d{2})'  # Simple decimal format

  # Line item patterns
  line_items:
    - '([A-Z]+)\s+(UPS[^0-9]*)\s+(\d+)\s+(\d+)\s+(\d+)\s+([A-Z0-9*-]+)\s+([^0-9]+)\s+([\d.]+)'
    - '([A-Z0-9*-]+)\s+.*?([\d,.]+)$'  # Simplified item pattern

# Field keywords for ML detection and flexible matching
field_keywords:
  subtotal:
    - "SUBTOTAL"
    - "SUB TOTAL"
    - "SUB-TOTAL"
    - "MERCHANDISE TOTAL"

  surcharges:
    - "SURCHARGES"
    - "SURCHARGE"
    - "FUEL SURCHARGE"
    - "MATERIAL SURCHARGE"
    - "AGN_SURCHARGE"

  shipping:
    - "SHIPPING"
    - "HANDLING"
    - "RESTOCK FEE"
    - "SHIPPING AND HANDLING"
    - "FREIGHT"

  total:
    - "USD TOTAL"
    - "TOTAL"
    - "AMOUNT DUE"
    - "GRAND TOTAL"
    - "FINAL TOTAL"

  vendor:
    - "SELLER"
    - "SCHLAGE"
    - "ALLEGION"
    - "VENDOR"
    - "FROM"

  customer:
    - "BILL TO"
    - "SHIP TO"
    - "CUSTOMER"
    - "SOLD TO"
    - "BUYER"

# OCR and processing settings
ocr_settings:
  dpi: 400  # High resolution for better OCR
  preprocessing_methods:
    - "basic"
    - "threshold"
    - "morphology"
    - "denoise"
  
  ocr_engines:
    - "tesseract"
    - "easyocr"
  
  confidence_threshold: 0.7  # Minimum confidence for accepting OCR results

# Validation settings
validation:
  required_fields:
    - "invoice_number"
    - "invoice_date"
    - "vendor_company"
    - "line_items"
    - "total"
  
  minimum_confidence: 0.5  # Minimum confidence for field acceptance
  accuracy_target: 90.0  # Target accuracy percentage

# Field importance weights for confidence calculation
field_weights:
  invoice_number: 0.20
  invoice_date: 0.15
  customer_po: 0.10
  subtotal: 0.20
  total: 0.20
  vendor_company: 0.10
  tracking: 0.05

# Fallback settings
fallbacks:
  enable_minimal_fallbacks: true  # Only apply fallbacks for critical missing data
  vendor_detection_keywords:
    - "SCHLAGE"
    - "ALLEGION"
  
  carrier_detection_keywords:
    - "UPS"
    - "FEDEX"
    - "USPS"

# Output settings
output:
  include_confidence_data: true
  include_raw_text: true
  save_intermediate_results: true
  confidence_threshold_for_output: 0.3
